### ISSUE TITLE
MY_Controller errors found.

### ISSUE THREAD

**Issue by claide** [filjoseph1989/rmc#1]
A PHP Error was encountered

Severity: Notice

Message: Undefined index: fragments

Filename: core/My_Controller.php

Line Number: 43
+++++++++++++++++++++++++++++++++++++++++

Severity: Warning

Message: Invalid argument supplied for foreach()

Filename: core/My_Controller.php

Line Number: 43Severity: Warning

Message: Invalid argument supplied for foreach()

Filename: core/My_Controller.php

Line Number: 43

**kindly close this issue if fixed.**

**Comment by filjoseph1989** [comment]
This problem encounter already has a solution.
